---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: javaweb-app-rc
spec:
  replicas: 3
  selector:
    matchLavels:
      app: javaweb-label
  template:
    metadata:
      name: javawebapp-pod
      labels:
        app: javaweb-label
    spec:
      containers:
      - name: javawebappcontainer
        image: ashokit/javawebapp
        ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: javaweb-service
spec:
  type: NodePort
  selector:
    app: javaweb-label
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30785
...