# Recreate straties
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: javawebapp-deployment
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: javawebapp-label
  template:
    metadata:
      name: javawebapp-pod
      labels:
        app: javawebapp-label
    spec:
      containers:
      - name: javawebapp-container
        image: ashokit/javawebapp
        ports:
         - containerPort: 8080
...
apiVersion: v1
kind: Service
metadata:
  name: javawebapp-service
spec:
  type: NodePort
  selector:
    app: javawebapp-label
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30785
...