---
apiVersion: v1
kind: Namespace
metadata:
  name: sumay-ns
---
apiVersion: v1
kind: Pod
metadata:
  name: javaweb-app
  labels:
    app: javaweb-label
  namespace: sumay-ns
spec:
  containers:
  - name: javaweb-container
    image: ashokit/javawebapp
    ports:
    - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: javaweb-service  
  namespace: sumay-ns
spec:
  type: LoadBalancer
  selector:
    app: javaweb-label  #pod-label
  ports:
    - port: 80 #host-port
      targetPort: 8080
   #   nodePort: 30785  #30K to 32.767K
...